### ISSUE TITLE
Improve workerTrain performance.

### ISSUE THREAD

**Issue by Cristy94** [cazala/synaptic#100]
Workers are great for training multiple networks (or a single one in a background thread) but the performance of the `workerTrain` function is pretty bad (it takes much longer than training on the main thread).

My first question is why is the memory buffer constantly being passed between the main thread and the worker?

Why isn't the initial memory hard-coded into the Worker code ([see this line](https://github.com/cazala/synaptic/blob/master/src/network.js#L503)) and sent back to the main thread when the training was completed?

Also, why are the events for activation/propagation sent from the main thread? This all back-and-forth with _activate_ and _propagate_ messages slows things down a lot (eg: because of this the worker is idle most of the time, waiting for messages). I see that in the current implementation, things are done like so:

- Main thread creates worker
- Main thread handles all the training logic except that the **activation** and **back-propagation** are done by the Worker when the main thread sends the `activate` and `propagate` events along with input  and output data AND the entire memory buffer (network).

Wouldn't it be much faster to do it like so:

- Main thread creates worker having hardcoded the initial network memory (structure) and the **entire training set**
- Worker handles all the training by itself, only emitting log messages once every X iterations.
- After training was completed the worker sends back to the main thread the new network structure (computed weights).

What was the reasoning of using the workers only for the activate/propagate function? I [this entire function](https://github.com/cazala/synaptic/blob/master/src/trainer.js#L248) should also be hard-coded into the worker so that the worker can train the network without having to wait for the _activate_ and _propagate_ events.

What do you think? I can implement those changes if there is no actual reason for having the training logic done in the main thread.

**Comment by cazala** [comment]
Just tagged a new release `1.0.5`
