### ISSUE TITLE
Main JavaScript file is missing from NPM install

### ISSUE THREAD

**Issue by ChrisAntaki** [cazala/synaptic#108]
First off, great work on this library!

For some reason, when using `npm install synaptic`, the main JavaScript file, `./src/synaptic`, is missing.

![synaptic](https://cloud.githubusercontent.com/assets/1216762/16677589/610bb6e2-448c-11e6-9b24-a6d86034b0e6.png)

To get the library working, I had to `git clone` this repository into the `node_modules` folder. Any chance the file `./src/synaptic.js` was missing when `npm publish` was last run?

**Comment by canastro** [comment]
Having the same issue, had to install the previous version.

**Comment by jtguzman** [comment]
Having the same issue here. NPM package is not working smoothly. Had to use v1.0.4

**Comment by menduz** [comment]
@cazala

**Comment by cazala** [comment]
@ChrisAntaki I just tagged a new release where this is fixed, I also replaced the old gulp building system with webpack, and made a few changes around the WebWorker training -> [v1.0.6](https://github.com/cazala/synaptic/releases)

**Comment by ChrisAntaki** [comment]
Thanks, looking forward to checking it out!
