### ISSUE TITLE
Support negative numbers?

### ISSUE THREAD

**Issue by shamoons** [cazala/synaptic#13]
How can we have inputs that are negative?

**Comment by cazala** [comment]
I haven't tested this much, but I added the option to use a [Hyperbolic Tangent](http://commons.wikimedia.org/wiki/File:TanhFunction.jpg) as the activation function, which outputs positive and negative values (opposed to the default [Logistic Sigmoid](http://commons.wikimedia.org/wiki/File:SigmoidFunction.png))

To set the activation function of a layer you can do the following:

```
myLayer.set({
    squash: Neuron.squash.TANH,
})
```

Other way would be to normalize your values between (0, 1) ? Let's say your inputs go from -1 to 1, the you would: `(input + 1) / 2` to normalize the input, and then: `(output * 2) - 1` to normalize the output back to (-1, 1)
