### ISSUE TITLE
Hopfield supports fromJSON

### ISSUE THREAD

**Issue by n-lavrenko** [cazala/synaptic#132]
![1471475919764](https://cloud.githubusercontent.com/assets/7901225/17756708/42246f7a-64ea-11e6-9879-16a33671dae9.jpg)

As we can see - new instance from json are not filled by data. 
Latest version, latest Chrome. Bug?

Thanks

**Comment by n-lavrenko** [comment]
I realized that this method returns new instance of Network class, but not return the same object. 
Could you please add this information into wiki?
Thanks

**Comment by cazala** [comment]
done -> https://github.com/cazala/synaptic/wiki/Networks#tojsonfromjson
