### ISSUE TITLE
trainAsync does not work for me.

### ISSUE THREAD

**Issue by MariasStory** [cazala/synaptic#137]
Hi I am trying the "XOR using the method trainAsync" example and trainAsync does not work for me.
---------------------Error---------------
[[PromiseStatus]]
:
"rejected"
[[PromiseValue]]
:
TypeError: Cannot read property 'rate' of undefined at Perceptron.worker (https://cdnjs.cloudflare.com/ajax/libs/synaptic/1.0.8/synaptic.min.js:1:23572) at e.workerTrain (https://cdnjs.cloudflare.com/ajax/libs/synaptic/1.0.8/synaptic.min.js:1:28694) at https://cdnjs.cloudflare.com/ajax/libs/synaptic/1.0.8/synaptic.min.js:1:28101 at e.trainAsync (https://cdnjs.cloudflare.com/ajax/libs/synaptic/1.0.8/synaptic.min.js:1:28071) at <anonymous>:23:9

Uncaught (in promise) TypeError: Cannot read property 'rate' of undefined(…)
------------------in the Synaptic.js file-------------------
1743	    // Copy the options and set defaults (options might be different for each worker)
1744	    var workerOptions = {};
1745	    if(options) workerOptions = options;
1746	    workerOptions.rate = options.rate || .2;  // this is where the error of undefined 'rate' parameter.
-------------------adding parameters to trainAsync--------------------
The parameters {rate: 0.15,iterations: 100,error: 0.0001}
-------------------New Error--------------------
cb50247c-b4fe-4567-bfea-2c7a8589d99b:1Uncaught SyntaxError: Unexpected token (

The error is in the messy first line of the blob starting with "function (t,i){function n(t){for"

Can someone point me to a working example?

**Comment by Jabher** [comment]
Can you please share an error message for non-minified version of Synaptic?

**Comment by MariasStory** [comment]
OK. It seems to work now. I was using a version from cdnjs.com.

The version from github/distr works.

It is mach slower in my quick test. So far.

**Comment by cazala** [comment]
the minified version does't work with the current worker implementation, since it builds the worker functions by converting the activation/propagation functions to strings and doing some replacements to send messages back and forth between the worker and the main thread. @Jabher by what i've seen from the branch you are working on, your implementation should work when minified right?

**Comment by Jabher** [comment]
@cazala yes, but it's breaking some APIs right now so I'm working on proposal of 2.x API with breaking changes right now

**Comment by MariasStory** [comment]
Shouldn't there be a test page where this kind of functionality is tested?
Like a best practice solution that should work. A play ground, that is referenced every time when some use case does not work.

**Comment by Jabher** [comment]
@MariasStory  Synaptic was added to CDNJS not by any of Synaptic contributors. 
https://github.com/cdnjs/cdnjs/issues/7991
CDNJS is not responsible for testing of a libraries, and a person who added this was not aware about the fact that minified version is not working properly.

It is distributed in a non-minified version by default in this repo, npm and so on, which is working.

**Comment by Jabher** [comment]
So, in brief - I've created a fix request on cdnjs, I'm working on minifiable version and you have a working and usable solution :)

**Comment by PeterDaveHello** [comment]
Hello all, CDNJS main maintainer here, sorry about that, as @Jabher says, we actually cannot make sure that minified files work 100%, I'm very sorry about that, I wonder if it's possible to create official minified synaptic distribution files here? Thanks.

**Comment by Jabher** [comment]
@PeterDaveHello There are some minification issues - if we'll just put dist/synaptic.min.js with same content as dist/synaptic.js will it work?

**Comment by PeterDaveHello** [comment]
@Jabher it'll work, BTW, is there any plan for the minification issues? All known minifier have that issues? Thanks.

**Comment by Jabher** [comment]
@PeterDaveHello any of them, I think. There's toString() with some regex replacements for function transfer into a Web Worker, and any optimization (like mangling or anything else) is breaking this regexes.
There is a fixed version, but due to the implementation details it contains breaking changes and will go into 2.x release.

**Comment by PeterDaveHello** [comment]
@Jabher thanks for your explanation! Before that just put dist/synaptic.min.js with same content as dist/synaptic.js will work good, thanks.

**Comment by Jabher** [comment]
@PeterDaveHello everything should be fine right now - https://github.com/cazala/synaptic/blob/master/dist/synaptic.min.js
If you need a version bump just let me know

**Comment by PeterDaveHello** [comment]
@Jabher it'll be great to have a version bump, btw, can it be real minified just as its naming "min.js"? Thank you very much!

**Comment by Jabher** [comment]
Version bump - done.

I'll try to investigate it, possibly spaces removal can work, still I'm not sure about it.

**Comment by PeterDaveHello** [comment]
@Jabher would you please also update the git tag? That's what our bot rely on, thanks.
