### ISSUE TITLE
 teach network to add to binary numbers?

### ISSUE THREAD

**Issue by SET001** [cazala/synaptic#152]
Is it possible to teach network to add two binary numbers? I suppose input layer to have 4 neurons 1-2 for first number and 3-4 for second. This is how I'm trying to do it:
```
const _ = require('lodash')
const synaptic = require('synaptic')
const Neuron = synaptic.Neuron
	Layer = synaptic.Layer,
	Network = synaptic.Network,
	Trainer = synaptic.Trainer,
	Architect = synaptic.Architect

var perc = new Architect.Perceptron(4, 10, 10, 10, 10, 3)
var trainer = new Trainer(perc)
var trainingSet = []

for (var i = 0; i<100; i++){
	var foo = []
	for(var j = 0; j<4; j++){
		foo.push(Math.round(Math.random()))
	}
	var a1 = parseInt(String(foo[0])+String(foo[1]), 2)
	var a2 = parseInt(String(foo[2])+String(foo[3]), 2)

	var sum = (a1+a2).toString(2)
	var res = _.padStart(sum, 3, '0').split('')
	trainingSet.push({
		input: foo,
		output: res
	})
}


console.log(trainer.train(trainingSet))
console.log(perc.activate([1, 1, 0, 1]))

```

but it gives wrong results after training - `{ error: 0.3249242775146285, iterations: 100000, time: 66568 }`
Also are there any rules to find out how much neurons and layers should I select for this task?

**Comment by SET001** [comment]
get it work. seems it only need 1 hidden layer and number on neurons in it relevant to accurasy

**Comment by Jabher** [comment]
I'm afraid we can encounter a misunderstanding here, possibly language issues.
You want us to make it work of you wanted to inform us that you made it work?

**Comment by SET001** [comment]
I already made it work , thanx
