### ISSUE TITLE
ReferenceError in Browser? Simple example for browser would be great.

### ISSUE THREAD

**Issue by TorbenOestergaard** [cazala/synaptic#153]
Hi

I have tried to apply synaptic on a webpage but get reference errors (as in issue #58): 
`Uncaught ReferenceError: Network is not defined`

I have referenced the synaptic in the header as suggested for issue #58:
`<head>
    <title></title>
    <script src="/myProject/dist/synaptic.min.js"></script>
</head>`

What am I doing wrong? And how do I make new predictions once a network model has been created?

Could you give very **simple example of how to use synaptic for regression in html**? An example could be based on a simple formula, e.g. y = sin(x1 * 2 Pi) * x2^4. The training set could be made using 100 random points with x1 and x2 between [0;1]. The 
![ann - synaptic - github question](https://cloud.githubusercontent.com/assets/10668865/19312960/061dde04-9095-11e6-9afe-f58e654c618e.PNG)

Such an example would be very much appreciated! :-)

**Comment by Jabher** [comment]
You should call `synaptic.Network`.
I've created simple example for you https://jsfiddle.net/stj265hy/
