### ISSUE TITLE
Examples by code

### ISSUE THREAD

**Issue by mathiasrw** [cazala/synaptic#156]
The examples are not helping as much as they could. 

The [XOR](http://caza.la/synaptic/#/xor) give the code

```html
var perceptron = new Architect.Perceptron(2,3,1);
perceptron.trainer.XOR(); 
```

but what I expect is not to see _that_ it works, but _how_ I can do it my self. 

I suggest the code in the examples are replaced with a version that can be copy/pasted that will show me how the nittygritty of a simple ecample works.

**Comment by cazala** [comment]
Yea, we have discussed this before, we plan to redo the docs showing more in-depth examples, it's gonna be part of v2.

As of what XOR does, here is an example, i'll leave it here in case it's helpful for you or anybody else: https://jsfiddle.net/53jmysba/
