### ISSUE TITLE
Clearing Context for LSTM

### ISSUE THREAD

**Issue by avikj** [cazala/synaptic#158]
Is it possible to clear the context for the LSTM provided in this library? This would be useful for using multiple sequences for training. For example, if training a network to perform binary addition, for every new set of numbers being added, context should be reset.

**Comment by cazala** [comment]
Yes, `myNetwork.clear()` clears all the traces keeping the weights and states ->  [link](https://github.com/cazala/synaptic/blob/master/src/network.js#L87)

**Comment by avikj** [comment]
Thanks for the quick reply! Is there documentation for the Network API and other modules anywhere?

**Comment by cazala** [comment]
There's some documentation on the [Wiki](https://github.com/cazala/synaptic/wiki), but it's not complete :/
