### ISSUE TITLE
Dynamic Learning Rate

### ISSUE THREAD

**Issue by shamoons** [cazala/synaptic#16]
The `Trainer` is pretty awesome. But I had wanted to use a dynamic learning rate. If you are agreed @cazala, I can write something up and submit a PR. Still waiting on your feedback for #12, by the way.

**Comment by cazala** [comment]
I just left a comment on #12, and yes having dynamic LR would be really interesting, if you code it just submit a PR and I ll add it to the library

**Comment by shamoons** [comment]
This wasn't tagged in a new release, was it?

**Comment by cazala** [comment]
I just released v0.1.7 with this new feature and #18 fixed, also I added this dynamic rate functionality to `workerTrain` method

**Comment by MentalGear** [comment]
Hey there,

Are dynamic learning rates eventually coming in a next release? If someone would give me a hint on what a optimal rate calculation and a function for dynamically improving the rate is, I could look into this.

**Comment by cazala** [comment]
@MentalGear learning rates can be fixed (i.e. `rate: 0.1`) or you can set multiple rates (i.e. `rate: [0.5, 01]`). In case you use multiple rates, they will be applied evenly according to the number of iterations you set, for example, if you set `iterations: 1000` and `rate: [0.5, 0.2, 0.1, 0.05]` the first 250 iterations will use `0.5` as the learning rate, from iteration 251 to 500 it will use `0.2`, from 501 to 750 `0.1` and from 751 to 1000 it will use `0.01`.
