### ISSUE TITLE
Stacked Autoencoder possible with sypnaptic.js?

### ISSUE THREAD

**Issue by andymakhk** [cazala/synaptic#163]
Hello, I'm toying around with stacked auto-encoder and try to have a feel on deep learning.
Assuming I'm doing an OCR task on a group of 7x7 pixels monochrome bitmap images of digits.
From my understanding, what I have to do is to:

- create a Perceptron(49, 25 ,49) and train the output to be the 49 original inputs
- create a Perceptron(25, 15, 25) and train the output to be the 25 inputs from previous hidden layer
- create a Perceptron(15, 10, 15) and train the output to be the 15 inputs from previous hidden layer
- finally glue them up again, and get Perceptron(49, 25, 15, 10) and use it for digit classification

But how to do the detaching/merging/copying of layers actually?
How would the codes actually look like? Thanks.

![autoenc](http://image.slidesharecdn.com/nnworkshop1-140829124424-phpapp02/95/neural-networks-and-deep-learning-15-638.jpg?cb=1409316389)
(image from: http://www.slideshare.net/anastasiiakornilova/neural-networks-and-deep-learn )

**Comment by Jabher** [comment]
I assume you probably want to do something like `Perceptron(49, 25, 15, 10, 15, 25, 49)`.
