### ISSUE TITLE
Receiving [NaN, NaN, ...] on LSTM traing

### ISSUE THREAD

**Issue by saxxi** [cazala/synaptic#165]
Hi,
  thanks for the library, I love it!

To understand LSTM and deep nets in general, I am trying add AI to the Connect-four game which I conveniently found a nice library to help me out.

Problem: after a couple of iterations when I use `LSTM.trainer.network.propagate` with
`LSTM.trainer.network.activate(input)` I get `[NaN, NaN, NaN, NaN, NaN, NaN, NaN]`.

Here's my attempt, would you get what I am doing wrong?
- https://github.com/saxxi/connect-four/blob/add-ai/src/Brain.js

[Maybe PR is easier to follow](https://github.com/saxxi/connect-four/compare/master...add-ai?expand=1) as is the point where I add the AI.
[Here's the full source code in this branch](https://github.com/saxxi/connect-four/tree/add-ai).

If this example works and you think it can help I'd like add it to your list of demos.
Thank you!

A.

**Comment by matthamil** [comment]
It looks like you might be passing a 2D array into propagate. This is will result in an `activate` return value of `NaN`. What is the value of the argument passed into `propagate`?

**Comment by squishybanana04** [comment]
Is the value you are using a 2 dimensional array?

I've had trouble with arrays before in synaptic try flattening it. I've found that the support and documentation is quite bad with LSTMs so I could be wrong.

**Comment by matthamil** [comment]
An error should probably be thrown if a 2D array is passed into these functions to prevent this.

**Comment by matthamil** [comment]
@squishybanana04 `activate` examples can be found in the documentation at https://github.com/cazala/synaptic/wiki/Networks#propagate

**Comment by saxxi** [comment]
You're both right, actually I was doing a `.propagate` with the player (`2 inputs`) instead of the move (`7 inputs`) and I've defined `7` as the number of total outputs in the declaration of the LSTM.

Thank you!

**Comment by MoritzGoeckel** [comment]
For any person who runs into the same problem: I had some NaNs in my previous training data. After that I only got NaNs as results, no matter what input. So clean your training data before you feed the network. If it contains NaNs it destroys your network.
