### ISSUE TITLE
[Question] What is the purpose of the optimize function in neuron.js and when is it used?

### ISSUE THREAD

**Issue by TrentWDB** [cazala/synaptic#167]
I'm looking over the code to try to better understand how everything works, and half the neuron code is this big chunk of pretty ambiguous optimization code that I'm not sure is necessary to actually run the library.

Can the library be ran without including the optimize function in neuron, and just be slower?

**Comment by Jabher** [comment]
You probably want to use `setOptimize(false)`
See example: https://github.com/cazala/synaptic/blob/a5fbefea5a69700384e2fe4c9fd82b2c50146c5f/test/synaptic.js#L421

Also you can have a quick look at [this doc](https://runkit.com/jabher/neural-network-from-scratch-in-js), it's my personal doc for one tech talk
