### ISSUE TITLE
Chatbots

### ISSUE THREAD

**Issue by abrad1212** [cazala/synaptic#171]
Is it possible to train a network with strings?

Currently I have tried this in a TrainingSet
`input: ["Hello", "Hi"],`
`output: ["Hello User"]`

If it's not possible this should be a feature.

**Comment by squishybanana04** [comment]
It looks like you don't need a neural network for this, all you need is a couple of if statements.

**Comment by I-n-d-e-r** [comment]
Take a look here: https://github.com/cazala/synaptic/issues/131

**Comment by abrad1212** [comment]
@squishybanana04 Well if statements takes all the fun of the Machine Learning!

Plus that would be way to many if statements.

**Comment by abrad1212** [comment]
@squishybanana04 Well if statements takes all the fun of the Machine Learning!

Plus that would be way to many if statements.

**Comment by squishybanana04** [comment]
You could use an object and do something like this:
var replies = {"Hello": "Hello User", "Hi": "Hello User"}

var response = replies[input]

Machine learning uses numbers as inputs to approximate functions or more complicated patterns. You won't need it for a simple input output function.

**Comment by Jabher** [comment]
Speaking of chat-based AI, we need to understand that in general there is no single lib for that (well, possibly Keras with some extensions can make it).
It's always NLP (natural language processing), then entities recognition (I cannot recall the proper name for that, sorry), then we know the context and some additional data of what we're saying. Then we can use AI to decide what idea we need to take as a reply. Then we have an additional stage which converts an idea into words (implementation depends).

But for you - yes, you probably need just a markov chain (e.g. markov.js), not an actual neural network.
