### ISSUE TITLE
Uncaught ReferenceError: i is not defined

### ISSUE THREAD

**Issue by andersonmadeira** [cazala/synaptic#18]
Hey guys, nice project you got here. But I'm getting some errors when I try to run just this simple test:

$(document).ready(function() {
	var Neuron = synaptic.Neuron,
    	Layer = synaptic.Layer,
    	Network = synaptic.Network,
    	Trainer = synaptic.Trainer,
    	Architect = synaptic.Architect;

	var percep = new Architect.Perceptron(2,3,1);
	var trainer = new Trainer(percep);

	trainer.XOR();

	var trainingSet = [
		{input: [0,0], output: [0]},
		{input: [0,1], output: [1]},
		{input: [1,0], output: [0]},
		{input: [1,1], output: [0]}
	];

	var callback = function (result) {
		console.log('error:', result.error, 'iterations:', result.iterations, 'time:', result.time);
	}

	trainer.workerTrain(trainingSet, callback);
});

I get the following error/msgs in the browser:
Resource interpreted as Script but transferred with MIME type text/plain: "blob:http%3A//localhost%3A3000/a985b008-bf1a-4bc1-91c2-8c5fefe667c8".
Uncaught ReferenceError: i is not defined

This is an nodejs + express simple app, with a public folder, in which we can find all js files and index.html.

Can anybody tell me what's wrong? Is it a bug? Or am I using the lib incorrectly?

**Comment by cazala** [comment]
I just tested it and I get the same error, it must be a bug. Since the `workerTrain` feature only works in the browser there are no tests for it in the building process. I ll try to take a look later today and push a fix.

**Comment by cazala** [comment]
I just tested it and I get the same error, it must be a bug. Since the `workerTrain` feature only works in the browser there are no tests for it in the building process. I ll try to take a look later today and push a fix.

**Comment by andersonmadeira** [comment]
I just checked the version embedded in the website and it seems to be working fine.

**Comment by cazala** [comment]
I just fixed this and pushed a new release to npm
