### ISSUE TITLE
Why I should use Synaptic instead of TensorFlow[1] by Google?

### ISSUE THREAD

**Issue by andreabazerla** [cazala/synaptic#180]
[1] [TensorFlow Playground](http://playground.tensorflow.org/)

**Comment by Jabher** [comment]
1.TensorFlow playground is not an actual TensorFlow, it's just a demo how neural nets work

**Comment by Jabher** [comment]
2. TensorFlow is Python/C++ library, it's very low-level in its core and is not intended to be used in same high-level API. Also it is totally not user-friendly (however, it's extremely flexible). On other hand, Synaptic is high-level library for network computations. Moreover, I'd rather say if you need neural net computations right now and you are asking this questions, you should prefer Keras, Caffe or Lasagne. They are intended to be performant, flexible and to provide every kind of layer entry-level data scientist. On other hand, Synaptic is just kind of "toy lib" right now. It is the only one nn framework in JS which is providing recurrent layers with nice API, but still toy'ish in questions of performance matters and some layers for data flow. Also it's not providing convolution layers. We do not have fast NN frameworks in JS right now (except keras.js, but it is kind of Keras player, not nn framework in general meaning of this word).

**Comment by Jabher** [comment]
3. Synaptic 2 is in stage of active development right now and it is planned to bring TensorFlow as one of computation backends - not in initial release, but in future releases. I hope that TF and plain CUDA computational backends will be implemented this spring.

**Comment by Jabher** [comment]
So - thank you for this question, it's really good one, but I do not have any really good answer for you right now. Come back in Feb or March, and I'll give you a list of reasons why should or should not you use Synaptic 2 instead of Keras, TensorFlow or any other NN lib 😸

**Comment by andreabazerla** [comment]
Thank you very much, Synaptic is amazing 👍 I'm confused about my project, but maybe I will use Synaptic because it's simple, documented and generic.

I suggest you to keep open this issue for future challenges about Synaptic VS TensorFlow.

**Comment by Jabher** [comment]
We will probably create a special doc for Synaptic2 about all of that stuff, so I think we can close it. You know, open/closed ratio is one of metrics of package health :)
