### ISSUE TITLE
Demo `Read from Wikipedia` not working

### ISSUE THREAD

**Issue by Bondifrench** [cazala/synaptic#181]
When trying to run the demo, I get redirected to this [page](http://caza.la/wiki) which returns a `404` error.

**Comment by ivanhuay** [comment]
+1

**Comment by Jabher** [comment]
@cazala ?

**Comment by bcatalin** [comment]
I guess some js file is missing

**Comment by OR13** [comment]
+1 I'm looking for a text prediction example.

**Comment by ElVisPL** [comment]
+1

**Comment by Vadizar** [comment]
Да, не работает.

**Comment by zammbi** [comment]
Such example would be nice. So +1

**Comment by cazala** [comment]
The source code is in this repo: https://github.com/cazala/synaptic-wikipedia if that helps.. It needs PHP to run though, and sadly the live demo is not hosted anymore.

**Comment by alexeypetrushin** [comment]
Maybe change the link in docs from not working demo to source code?
