### ISSUE TITLE
BUG in LayerConnection?

### ISSUE THREAD

**Issue by pauljohnleonard** [cazala/synaptic#184]
The is a weights parameter is an array right?

`function LayerConnection(fromLayer, toLayer, type, weights)`

But it is used like a scalar 

 `var connection = from.project(to, weights);`

Should this be (If weights is defined and is an array) ?

 `var connection = from.project(to, weights[there][here]);`

**Comment by Jabher** [comment]
We're connecting layers, not separate nodes here.
And we need all of the weights here, they will be resolved individually for each neuron - but inside the connection.

In future, please, use code references (with link), not copy-pasted code, it makes difficult to understand the context of question.
