### ISSUE TITLE
Question: If I create a custom connection structure of neurons, and activate the first layer, how do I get the output when the activation reaches the last layer (output)?

### ISSUE THREAD

**Issue by viziionary** [cazala/synaptic#191]
If I create a custom connection structure of neurons, and activate the first layer, how do I get the output when the activation reaches the last layer (output)?

I'm working with neurons at the lowest level of your library, arranging them in specific way, manually. I'm not using layers, I'm simply storing a series on neurons in an array and calling that a layer. I have a network for example, 3 neurons in an array, each projected to 3 other neurons in the next array, so neurons A1, A2, and A3 (my input layer), are projected to neurons B1, B2, B3 (my hidden layer), and those are each connected to neurons C1, C2, and C3 (my output layer). The only thing I'm not understanding, is how to listen to the output neurons so that I can read their output manually, when my activation of the input neurons propagates through the network and reaches the output layer. How do I read the output of a custom network like this, in other words?

    function create(inputSize, outputSize, layers) {
      if (!layers || layers < 3) layers = 3;
      function Brain() {
        var that = this;
        this.brain = [];
        this.input = function(array) {
            for (var i1 = 0; i1 < inputSize; i1++) {
              that.brain[0][i1].activate(array[i1]);
            }
          }
          //we also of course need a function to listen for the output and communicate 
          //that to the simulation, but I'm not sure how to read the output yet. 
          //I couldnt find that in the docs <<< My Problem
      }
      var adam = new Brain();
      for (var i1 = 0; i1 < layers; i1++) {
        var layer = [];
        var size = 0;
        if (i1 == 0) {
          size = inputSize;
        } else if (i1 == layers) {
          size = outputSize;
        } else {
          size = Math.round((inputSize + outputSize) / 2);
        }
        for (var i2 = 0; i2 < size; i2++) {
          var neuron = new Neuron();
          for (var i3 = 0; i3 < layer.length; i3++) {
            neuron.project(layer[i3]);
          }
          layer.push(neuron);
        }
        adam.brain.push(layer);
      }
      return adam;
    }

**Comment by pauljohnleonard** [comment]
From the docs. 

```
var A = new Neuron();
var B = new Neuron();
A.project(B);

A.activate(0.5); // 0.5
B.activate(); // 0.3244554645
```

**Comment by viziionary** [comment]
@pauljohnleonard ohh, ok so simply activating the projected neuron gives the result. I understand now, sorry.
