### ISSUE TITLE
Any way to remove projections?

### ISSUE THREAD

**Issue by viziionary** [cazala/synaptic#192]
How can I safely remove projected connections between individual neurons? I see where the connection objects are located but I'm not sure how to remove one. 

The reason I need to remove connections is because I'm using an evolutionary method where one starts with a simple structure, passes an input, scores the fitness based on the output, then mutates the structure slightly, and continues to repeat this until one of the mutations results in a good output, after which that mutated child becomes the new parent, rinse and repeat. 

Like this: https://www.youtube.com/watch?v=qv6UVOQ0F44

If you only have a mutation which adds connections and doesn't have an equal chance of removing them, the mutated structure will simply gain and gain and gain connections each time it evolves when it might need to remove certain connections in order to evolve again.

**Comment by wagenaartje** [comment]
I'm not sure what you mean by removing projections. However I think there is a way to remove connections. What you can do is convert your network to a JSON. This will create a dictionary like so {'neurons':[], 'connections':[]} in which there is a list of all individual neurons and connections. So you could just remove a connection from that array by splicing as follows:

```
var network = new synaptic.Architect.Perceptron(2,2,1);
var networkJSON = network.toJSON();
networkJSON.connections.splice(index,1);
network = synaptic.Network.fromJSON(networkJSON);
```

I tested this real quick by activating the resulting network and it doesn't seem to cause a problem at all, unless you would remove one of the input or output connections I presume.

**Comment by wagenaartje** [comment]
[Neataptic](https://github.com/wagenaartje/neataptic) actually has the built-in function `disconnect()`, which is the opposite of `connect()`. So you can easily remove projections.

**Comment by viziionary** [comment]
@wagenaartje thanks so much I hadnt found that library yet. Very useful.
