### ISSUE TITLE
How are weights being set?

### ISSUE THREAD

**Issue by lucas-aragno** [cazala/synaptic#210]
I'm researching into NN and i found this library, but I'm not sure how is synaptic setting the weights on the hidden layers connections on the examples. It does it by itself?

**Comment by wagenaartje** [comment]
When you initialise a network, with for example `new Architect.Perceptron(1,2,1);` all the connections in the network get a random weight:

```javascript
Neuron.connection = function Connection(from, to, weight) {

  if (!from || !to)
    throw new Error("Connection Error: Invalid neurons");

  this.ID = Neuron.connection.uid();
  this.from = from;
  this.to = to;
  this.weight = typeof weight == 'undefined' ? Math.random() * .2 - .1 :
    weight;
  this.gain = 1;
  this.gater = null;
}
```
(_notice this.weight_)

So yes, it does it by itself randomly. You can however pass the `weight` argument, which lets you set the weight yourself.

And ofcourse, during backpropagation, the weights get modified ( but I hope you were already aware of this ;) ).

**Comment by lucas-aragno** [comment]
@wagenaartje Thank you! yes i was aware of that but just wasn't sure how the weights were set initially. I'll search for the backpropagation code, are the weights also being optimized on that step?

**Comment by wagenaartje** [comment]
So the backpropagation code is:

```javascript
  // back-propagate the error
  propagate: function(rate, target) {
    [...]

    // learning rate
    rate = rate || .1;

    // adjust all the neuron's incoming connections
    for (var id in this.connections.inputs) {
      var input = this.connections.inputs[id];

      // Eq. 24
      var gradient = this.error.projected * this.trace.elegibility[input.ID];
      for (var id in this.trace.extended) {
        var neuron = this.neighboors[id];
        gradient += neuron.error.responsibility * this.trace.extended[
          neuron.ID][input.ID];
      }
      input.weight += rate * gradient; // adjust weights - aka learn
    }

    // adjust bias
    this.bias += rate * this.error.responsibility;
  },
```

So if you backpropagate a neuron, the weights of its incoming connections will get updated in order to have an output with less error. So the weights get optimized there!

**Comment by lucas-aragno** [comment]
I saw that piece of code yestarday this library seems like an amazing thing! I started using to prototype some things for my project!

Thanks for the Help! 😄
