### ISSUE TITLE
How to update the activation function?

### ISSUE THREAD

**Issue by TheInvoker** [cazala/synaptic#216]
If I create a network like this

			var learningRate = .3;
			var Layer = synaptic.Layer;
			var Network = synaptic.Network;
			
			// create the network
			var inputLayer = new Layer(2);
			var hiddenLayer = new Layer(3);
			var hiddenLayer2 = new Layer(3);
			var outputLayer = new Layer(1);
			inputLayer.project(hiddenLayer);
			hiddenLayer.project(hiddenLayer2);
			hiddenLayer2.project(outputLayer);
			var myNetwork = new Network({
				input: inputLayer,
				hidden: [hiddenLayer, hiddenLayer2],
				output: outputLayer
			});

How can I set the activation function of the neurons to be like Relu from here

https://github.com/wagenaartje/neataptic/wiki/Activation

Thanks

**Comment by wagenaartje** [comment]
You can set the squash of all neurons in a layer by doing the following:

``` javascript
var hiddenLayer = new Layer(3);
hiddenLayer.set({squash: Neuron.squash.RELU});
```
