### ISSUE TITLE
[ReferenceError: Blob is not defined]

### ISSUE THREAD

**Issue by fix2015** [cazala/synaptic#222]
Hi, i tried trainAsync func in nodejs and i had this in console "[ReferenceError: Blob is not defined]". Maybe someone have this already?

**Comment by zammbi** [comment]
Looks like this method doesn't work for node.js going by what the wiki says. 

> This method doesn't work in node.js, and it might not work on every browser (it has to support Blob and WebWorker's).
https://github.com/cazala/synaptic/wiki/Trainer

**Comment by cazala** [comment]
trainAsync uses Blob and WebWorkers, and currently it is only supported in nodejs

**Comment by pumpkinp** [comment]
and so

**Comment by FallingSnow** [comment]
> trainAsync uses Blob and WebWorkers, and currently it is only supported in nodejs

Did you mean to say not supported on nodejs?
