### ISSUE TITLE
Normalization, De-Normalization?

### ISSUE THREAD

**Issue by silentrob** [cazala/synaptic#25]
This project looks amazing, and I have't played with it yet, but I was curious if the inputs need to be pre-normalized? 

If not, would this make for a good helper or utils library to compliment synaptic or do you have any tips on that?

**Comment by cazala** [comment]
yes, the inputs need to be normalized. Depending on the activation function you use, the inputs/outputs will be (0, 1) or (-2, 2) - either for Logistic Sigmoid or Hyperbolic Tangent. There are no helpers in the lib so far, but it would be great to have some utils for these tasks.

**Comment by cloppy** [comment]
Why is the range of the hyperbolic tangent activation function (-2, 2) and not (-1, 1)?

**Comment by nickpoorman** [comment]
@silentrob I wrote a module for this exact purpose. It's super simple. https://www.npmjs.com/package/scale-number-range

**Comment by silentrob** [comment]
Nice work @nickpoorman. Pretty much a one line npm module. haha

**Comment by nickpoorman** [comment]
@silentrob Also, just published https://www.npmjs.com/package/one-hot for one-hot encoding of non-numerical (string) values.
