### ISSUE TITLE
Homepage Demo?

### ISSUE THREAD

**Issue by woojoo666** [cazala/synaptic#26]
Where can I find the code for the demo on the [homepage](http://synaptic.juancazala.com/#/)? I inspected the page but I couldn't find the script controlling the canvas, let alone the creature.js and world.js scripts. I would really like to see all the code behind the demo, is it possible for somebody to direct me to the source?

**Comment by silentrob** [comment]
It was really hard to find.
I think maybe running in a web worker? But it showed up as VM106.js

Here are the contents.

    $(function()
    {
      var canvas = $("#canvas")[0];
      var ctx = canvas.getContext('2d');

      var num = 10;
      var fps = 100;

      canvas.width = $('#canvas-container').width();
      $(window).resize(function(){
        var width =  $('#canvas-container').width();;
        canvas.width = witdh;
        world.width = width;
      })

      var world = {
        width: 0,
        height: 0,
        creatures: [],
        width: canvas.width,
        height: canvas.height,
        context: ctx
      }

      // popullate
      for (var i = 0; i < num; i++)
      {
        var x = Math.random() * world.width;
        var y = Math.random() * world.height;

        world.creatures[i] = new Creature(world, x, y);
        world.creatures[i].velocity.random();
      }

      var targetX = function(creature){
        var cohesion = creature.cohesion(world.creatures);
        return cohesion.x / world.width;
      }

      var targetY = function(creature){
        var cohesion = creature.cohesion(world.creatures);
        return cohesion.y / world.height;
      }

      var targetAngle = function(creature){
        var alignment = creature.align(world.creatures);
        return (alignment.angle() + Math.PI) / (Math.PI*2);
      }

      var loop = function()
      {
        // fade effect
        ctx.globalAlpha=0.2;
        ctx.fillStyle='rgb(244, 244, 244);';
        ctx.fillRect(0,0,world.width, world.height);
        ctx.globalAlpha=1;

        // update each creature
        var creatures = world.creatures;
        creatures.forEach(function(creature)
        {
          // move
          var input = [];
          for (var i in creatures)
          {
            input.push(creatures[i].location.x);
            input.push(creatures[i].location.y);
            input.push(creatures[i].velocity.x);
            input.push(creatures[i].velocity.y);
          }
          var output = creature.network.activate(input);
          creature.moveTo(output);

          // learn
          var learningRate = .3;
          var target = [targetX(creature), targetY(creature), targetAngle(creature)];
          creature.network.propagate(learningRate, target);

          // draw
          creature.draw();
        });
        if (location.hash == "#/")
          setTimeout(loop, 1000/fps);
      }

      // blastoff
      loop();
    });

**Comment by jzjzjzj** [comment]
Check out `gh-pages` branch - https://github.com/cazala/synaptic/tree/gh-pages/scripts/homepage

**Comment by cazala** [comment]
@jzjzjzj is right, the homepage and all the demos are in the gh-pages branch

**Comment by woojoo666** [comment]
ah, missed that. Thanks a bunch!

**Comment by GospodinNoob** [comment]
@woojoo666 You launch the demo without errors? The page isn't worked correctly for me. Can you help, please?

**Comment by woojoo666** [comment]
@GospodinNoob doesn't work for me anymore, seems to freeze the page

**Comment by wagenaartje** [comment]
@woojoo666 very weird. I'm having the same issue, I think it has something to do with chrome. I created a JSFiddle to run the demo here: 

[JSFiddle (homepage demo)](https://jsfiddle.net/wagenaartje/4516xtze/3/)

It works fine on Edge but not on Chrome.

**Comment by reicek** [comment]
I really liked this demo, great work @cazala ! Looking forward for v2.

I'm making a remake of the demo on the homepage, adding a lot more complexity to the simulation (aging, reproduction, species, etc). I need to polish lots of the code and add documentation. I'll make sure to mention the source and author properly.

If anyone is interested, [this is the repository](https://github.com/reicek/AI-world). I plan to eventually use it in an article about neural networks in JS.

**Comment by wagenaartje** [comment]
@reicek interesting! Maybe use Github Pages so we can directly run your demo?

**Comment by reicek** [comment]
Sure @wagenaartje ! Adding a Github page for the demo sounds like a good idea.

**Comment by reicek** [comment]
@wagenaartje Added a [Github page](https://reicek.github.io/AI-world/) for the project.
