### ISSUE TITLE
Chinese document translation

### ISSUE THREAD

**Issue by noraincode** [cazala/synaptic#280]
I want to translate the document into Chinese to help more Chinese developers participate in the development of this project, and if possible, I will submit a MR about the translation of this README document first, and the content of WIKI in the future will be gradually translated into Chinese

**Comment by cazala** [comment]
Sounds great! Please send a PR and feel free to create wiki pages

Sent from my iPhone

On Oct 31, 2017, at 12:01 PM, noraincode <notifications@github.com<mailto:notifications@github.com>> wrote:


I want to translate the document into Chinese to help more Chinese developers participate in the development of this project, and if possible, I will submit a MR about the translation of this README document first, and the content of WIKI in the future will be gradually translated into Chinese

**Comment by noraincode** [comment]
@cazala It's midnight in China now, I might complete the translation of the README document tomorrow >3<
