### ISSUE TITLE
how to add constraints for the output?

### ISSUE THREAD

**Issue by Gorash** [cazala/synaptic#290]
Hello,

I would like to know how could I add constraints for the outputs.

I have in input vectors (36 vectors of 5 integers), synaptic me returns the same number of vectors whose values can be modified to correspond to the training (on the basis of known transformations). However, for 4 of its integers, only certain combinations can be used, I would like to be able to provide the list directly to the LSTM in order to optimize the answers and accelerate learning. In addition, the allowed combination list may vary from one simulation to another (between 150 and 3000).

Thank you for helping me.

**Comment by Pummelchen** [comment]
You could process the 4 integers in a dedicated LSTM and feed that output into your main LSTM as another input.

**Comment by Gorash** [comment]
Thanks
As suggested, the dedicated LSTM, who use the 4 integers, takes care of the white-list, during the learning the white-list is used to check the exit.
