### ISSUE TITLE
How do I save a trained Neural Network to a file?

### ISSUE THREAD

**Issue by bootsie123** [cazala/synaptic#323]
Hi. I'm trying to save a neural network when it finishes training so that It can be used again sometime in the future and no other training is required. What I'm trying to do is save it to a file. I have tried using toJSON() and then saving it to a json file and loading it with fromJSON(). However, it doesn't seem to have kept what it actually learned. The other thing I'm looking into is possible using the standalone function and then seeing if it's possible to store the function to a file. Am I doing this correctly or is there a different/better way to do this?

**Comment by chrisdothtml** [comment]
https://github.com/cazala/synaptic/wiki/Networks#tojsonfromjson

**Comment by chrisdothtml** [comment]
If [toJSON/fromJSON](https://github.com/cazala/synaptic/wiki/Networks#tojsonfromjson) aren't working, it may have to do with how your network is setup. Can't say without seeing your code
