### ISSUE TITLE
Can't save to JSON?

### ISSUE THREAD

**Issue by madser123** [cazala/synaptic#339]
Hi. I've been trying to save my network to a file so that i can use it without training it. The "toJSON" doesn't seem to create a file in the directory where my files are. 

I'm doing this in the browser not via node.js.

I'm running the HTML file directly from my pc into chrome. I'm not using a server of any kind.

EDIT: it is now also giving me the error: fromJSON is not a function

**Comment by termxz** [comment]
Calling toJSON() function only makes an exact copy of the neural network and turns it into JSON format. Web Applications are not able to interact with the local file system, therefore you can't actually make a JSON file.

**Comment by Pummelchen** [comment]
Use Node.exe not Chrome or store the network in a cookie or cloud storage ..

**Comment by madser123** [comment]
@Pummelchen Thanks! Never thought of cookies as an option. Any chance you have a code snippet as an example of how to do this? Sorry for asking so much..
