### ISSUE TITLE
Custom Logs in workerTrain

### ISSUE THREAD

**Issue by oktabyte** [cazala/synaptic#45]
It seems that custom logs don't work properly in workerTrain, while the same inputs (stripping the callback) do work just fine with the basic train.

The Code used: (pastebin to reduce reading size)
http://pastebin.com/DJYRe1X5

Executed in the most recent Google Chrome browser, and tested in firefox for completion

**Comment by cazala** [comment]
Hi @oktabyte, I just pushed a new release, with several bugs fixed, one of them was an error regarding the scheduled tasks on workers. Could you test it again using the latest tag (v.1.0.0) to check if it is the same issue?

**Comment by oktabyte** [comment]
Report: It seems to be fixed. Finally I can see my calculations happen in real time and no interface freezes.

**Comment by cazala** [comment]
awesome :)
