### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by kaaninel** [cazala/synaptic#48]
I am doing something really wrong :S

**Comment by kaaninel** [comment]
var slice = [].slice;

this.Network= function() {
  var layers, name;
  name = arguments[0], layers = 2 <= arguments.length ? slice.call(arguments, 1) : [];
  return {
    Name: name,
    LearningRate: .12,
    MaxIteration: 2000,
    MinError: 1e-8,
    MeanSquareError: 1,
    CurrentIteration: 0,
    InputSet: [],
    DesiredSet: [],
    Network: new Synaptic.Architect.Perceptron(layers),
    RandomInputSet: function(c, max) {
      var i, j, q, ref;
      for (i = j = 0, ref = c; j <= ref; i = j += 1) {
        q = Math.random() * max;
        this.InputSet.push(Converter.ToBinary(q, 7));
      }
    },
    CreateDesiredSet: function(func) {
      var i, j, len, q, ref;
      ref = this.InputSet;
      for (j = 0, len = ref.length; j < len; j++) {
        i = ref[j];
        q = func(i);
        this.DesiredSet.push(Converter.ToBinary(q, 63));
      }
    },
    TrainA: function(input, desired) {
      this.Network.activate(input);
      this.Network.propagate(this.LearningRate, desired);
    },
    Train: function() {
      var q;
      while (this.CurrentIteration < this.MaxIteration) {
        q = Math.floor(Math.random() * this.InputSet.length);
        this.Network.activate(this.InputSet[q]);
        this.Network.propagate(this.LearningRate, this.DesiredSet[q]);
        this.CurrentIteration++;
        if (this.CurrentIteration % 500 === 0) {
          console.log(this.CurrentIteration / this.MaxIteration);
        }
      }
    },
    Run: function(input) {
      return Converter.ToNumber(this.Network.activate(Converter.ToBinary(input, 7)));
    }
  };
};

**Comment by cazala** [comment]
What's the size of your input layer? The inputs you feed to the network have to be the same length as your input layer. In that example you are providing inputs of variable sizes (depending on the number that you are converting to binary). You should fix all your inputs to the size of your input layer before activating the network. You can simply pad with 0's, ie: if your input layer has 10 neurons, instead of activating [1,0,1,0] use [0,0,0,0,0,0,1,0,1,0]

**Comment by kaaninel** [comment]
```javascript
this.Converter = {
  ToBinary: function(n, f) {
    var c, i, j, ref, ref1;
    c = [];
    while (n >= 1) {
      c.unshift(Math.floor(n % 2));
      n = Math.floor(n / 2);
    }
    for (i = j = ref = c.length, ref1 = f; j <= ref1; i = j += 1) {
      c.unshift(0);
    }
    return c;
  },
  ToNumber: function(a) {
    var i, n;
    n = 0;
    for (i in a) {
      if (Math.round(a[a.length - i - 1] === 1)) {
        n += Math.pow(2, i);
      }
    }
    return n;
  }
};
```
8,32,32,64 layer neuron counts. 
i am giving 8 input and 64 output. 
example input : [0, 0, 0, 0, 1, 0, 0, 1] -> length: 8
example desired: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0] -> length : 64

**Comment by cazala** [comment]
In this line: 
```
new Synaptic.Architect.Perceptron(layers)
```
Currently you cant provide the layers as an array, they have to be provided as separate arguments. Making the constructor to support the layers definition as an array is actually a nice feature that could be added to the Architect, but as a workaround for now you could simply create a simple factory function to handle that for you, like:

```
var makePerceptron = (function() {
    function dummy(args) {
        return Architect.Perceptron.apply(this, args);
    }
    dummy.prototype = Architect.Perceptron.prototype;
    return function() {
        return new dummy(arguments[0]);
    }
})();
```

and then you just call it like:

```
Network: makePerceptron(layers),
```

**Comment by kaaninel** [comment]
I did that another way but still same result

**Comment by cazala** [comment]
Okay, I can see that you are padding your dataset:

```
this.InputSet.push(Converter.ToBinary(q, 7));
---
this.DesiredSet.push(Converter.ToBinary(q, 63));
---
return Converter.ToNumber(this.Network.activate(Converter.ToBinary(input, 7)));
```

but then on the example that displays the NaN's you are providing an input of length 4, instead of 8:

![code](http://i.imgur.com/Hs2DKVz.png)

**Comment by kaaninel** [comment]
Coffee script related problem i think. second parameter of tobinary was undefined always i fix it and now it works. Thanks so much. One last thing how we take mse in network. it gives always same result i guess need much more training

**Comment by cazala** [comment]
[This](https://github.com/cazala/synaptic/blob/master/src/trainer.js#L693) is how we compute the MSE for all the outputs of the network, against their target:

```
MSE: function(target, output)
  {
    var mse = 0;
    for (var i in output)
      mse += Math.pow(target[i] - output[i], 2);
    return mse / output.length;
  }
```

MSE works best for regression, while cross-entropy usually works better for classification problems.
