### ISSUE TITLE
Test uses opposite activation

### ISSUE THREAD

**Issue by irrationalistic** [cazala/synaptic#51]
First, this is an awesome library! I've been trying to grasp the concept of neural networks and this is a great place for me to test stuff out. Thanks so much for all the work you've put into it!

Minor thing, but as I have been browsing the source, I noticed that you are testing the opposite values here:
https://github.com/cazala/synaptic/blob/master/test/synaptic.js#L91
https://github.com/cazala/synaptic/blob/master/test/synaptic.js#L137

**Comment by cazala** [comment]
good catch, thank you! I'm glad you like the library (:

**Comment by irrationalistic** [comment]
Dang, and you are fast too!
