### ISSUE TITLE
broken link for `Discrete Sequence Recall`

### ISSUE THREAD

**Issue by timqian** [cazala/synaptic#54]
the broken link: http://synaptic.juancazala.com/dsr.html

I find the link here: https://github.com/cazala/synaptic/wiki/Trainer#dsr

**Comment by cazala** [comment]
I just fixed it, the actual link is: http://synaptic.juancazala.com/#/dsr
thank you !

**Comment by jmadan** [comment]
Seems like the domain has expired. 
<img width="1328" alt="screen shot 2017-09-24 at 7 24 29 pm" src="https://user-images.githubusercontent.com/220452/30781209-25dc5d94-a15e-11e7-8949-df7ea15c408e.png">

**Comment by wagenaartje** [comment]
It has been, as has been said before, moved to a _new_ domain: http://caza.la/synaptic/#/dsr
