### ISSUE TITLE
How to use standalone() to reduce runtime

### ISSUE THREAD

**Issue by hmfoster** [cazala/synaptic#57]
Loving synaptic.js so far after just a day playing with it! 

I'm wondering how to properly use the standalone function to avoid retraining a network when run through node.js. For example, let's say I set up a network named `ganglia` in a file called "network.js" and run the following code:
```
var trainedGanglia = ganglia.standalone()
module.exports = trainedGanglia
```
If I then create a new file called, "trained.js" and require network.js like so:
```
var trained = require('./network.js')
trained([0.12, 0.42])
```
I get the correct output, but, as expected, only after the network is trained in network.js, which doesn't reduce the amount of time to run this file in node.js at all. Therefore, I'm not sure what you mean in the documentation when you say in the documentation that standalone() returns a function that has no dependencies on Synaptic etc... I see how the returned function itself doesn't have any dependencies, but I don't understand how this is useful. Could you please explain this further or give an example?

Thank you!

**Comment by cazala** [comment]
After you train the network, you can get the standalone function, convert it to locale string, and store it in a new .js file. Then just load that .js file and use that function the same way you would use `yourNetwork.activate` and it should produce the same output :)

**Comment by hmfoster** [comment]
Oh great! That sounds like it's perfect for what we're trying to do. Thanks so much!

**Comment by hmfoster** [comment]
One small problem...it looks like the npm version doesn't have the latest commit that fixes the problem with the standalone function. While we can fix it locally, we are planning to deploy our project. Any idea how long before the npm version is updated? Thanks!

**Comment by cazala** [comment]
i just released a new tag v1.0.2

**Comment by hmfoster** [comment]
Great! Thank you so much; really enjoying the library.

**Comment by cazala** [comment]
np! (:
