### ISSUE TITLE
I can't test in my browser...

### ISSUE THREAD

**Issue by frollino** [cazala/synaptic#58]
I'm trying to use synaptic in a web page but I have some errors like:
ReferenceError: require is not defined synaptic.js:53:4
ReferenceError: module is not defined layer.js:2:0
TypeError: Neuron is not a constructor layer.js:19:17

so I think there is a problem in my configuration. I have seen the "test" directory of the project where there must be a file test_browser.html... but I can't find it! Was it deleted?

Where can I find an example of web page where the synaptic.js is used?

Thanks!

**Comment by SkY3r** [comment]
Not using Node.js?

If you are using only HTML try this: https://github.com/cazala/synaptic/blob/master/dist/synaptic.min.js

**Comment by cazala** [comment]
@frollino as SkY3r said, you have to use the file from `/dist` directory if you want to run synaptic on the browser

```html
<script src="dist/synaptic.min.js"></script>
```

**Comment by frollino** [comment]
thanks!

Il 09/09/2015 19:35, Juan Cazala ha scritto:
