### ISSUE TITLE
Creating own squashing function

### ISSUE THREAD

**Issue by Harry27PL** [cazala/synaptic#66]
I want to create own squashing function. I have tried this way to assign my function to the hidden layer neurons:

```javascript
    var inputLayer = new Layer(1),
        hiddenLayer = new Layer(3),
        outputLayer = new Layer(1);

    inputLayer.project(hiddenLayer);
    hiddenLayer.project(outputLayer);

    var customFunction = function(x, derivate) {
        // some code
    };

    for (var k in hiddenLayer.list) {
        var neuron = hiddenLayer.list[k];
        neuron.squash = customFunction;
    }

    return new Network({
        input: inputLayer,
        hidden: [hiddenLayer],
        output: outputLayer
    });
```

but it seems to me that this function isn't activating during the activation of the network at all. The network always returns the same result for every input data. When I insert into a function some alert() or console.log(), nothing happens on activation.

I also tried it on an existing function from Synaptic.

```javascript
    var customFunction = Neuron.squash.TANH;
```

It works

```javascript
    // function copied from Neuron.squash.TANH;
    var customFunction = function(x, derivate) {
      if (derivate)
        return 1 - Math.pow(Neuron.squash.TANH(x), 2);
      var eP = Math.exp(x);
      var eN = 1 / eP;
      return (eP - eN) / (eP + eN);
    };
```

It doesn't works, same as with my custom function.

**Comment by cazala** [comment]
currently it is not supported to use custom activation functions on optimized networks, if you want to use your own function you will have to set your network in the following way: `myNetwork.setOptimize(false);`

**Comment by Harry27PL** [comment]
Thanks!

**Comment by cazala** [comment]
np (:
