### ISSUE TITLE
Strange JavaScript Syntax

### ISSUE THREAD

**Issue by ohenepee** [cazala/synaptic#69]
Juan, could you please be a little kind by telling me what that `+` sign is doing before the `localStorage` in the snippet below... I guess I'm a newbie on this one

`Wiki.time = localStorage.getItem("time") ? +localStorage.getItem("time") : 0;`

**Comment by menduz** [comment]
Localstorage only can handle strings. The + is used to cast the value as a
number. Saludos

**Comment by ohenepee** [comment]
Wow! that's something u don't find in the books I guess.... :P Thanks @menduz

**Comment by vigneshwerv** [comment]
@ohenepee For future reference, in case someone wants to read up on it this page has the documentation for the + unary operator: https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript
