### ISSUE TITLE
Advice on setting connection weights manually

### ISSUE THREAD

**Issue by cjsauer** [cazala/synaptic#86]
Hi there. Quick question: how would you advise setting all weights manually when projecting layers onto others? What should the `weights` parameter in `layer.project(layer, type, weights)` look like? An array of arrays? And are the weights always values between 0 and 1? 

Thanks for your help, and for an awesome project!

**Comment by cazala** [comment]
@cjsauer `weights` would be a number between 0 and 1. And that value would be applied as the weight for all the connection between the two connected layers. If you want to set the weights individually, you will have to do so manually, by accessing the neurons in that layer (`layer.list`) and all the connections on each neuron (`neuron.connections`) and setting each `connection.weight`. An easier way might be to export the whole network to json (`myNet.toJSON()`), then tweaking the values manually, and generating a new network using the modified json (`Network.fromJSON()`)

**Comment by cjsauer** [comment]
Thanks @cazala! I was able to set the weights by manually accessing each connection between neurons. I appreciate the help!
