### ISSUE TITLE
Please put up a working example for node and browser

### ISSUE THREAD

**Issue by akshay-since1987** [cazala/synaptic#88]
For people who do not know how to use this library, it would be great, if you could put up a complete end to end working example so that we can get started.

**Comment by UniqueFool** [comment]
You can view the HTML markup of the website, and you will find the examples there to be pretty self-contained, I just ended up using copy & paste to get going.

**Comment by cazala** [comment]
@akshay-since1987 The source of the demos/examples can be found in the branch [gh-pages](https://github.com/cazala/synaptic/tree/gh-pages)

**Comment by andymakhk** [comment]
And the wikipedia example is in [this repos](https://github.com/cazala/synaptic-wikipedia)

Thanks cazala for the great examples. They're really easy to digest :)
