### ISSUE TITLE
workingTrain and `cost` option

### ISSUE THREAD

**Issue by qrpike** [cazala/synaptic#90]
When using the workerTrain it seems you can't pass the cost param in.

eg:

```
var trainParams = {
    cost: Trainer.cost.CROSS_ENTROPY,
}
trainer.workerTrain( data, callback, trainParams );

```

**Comment by cazala** [comment]
mmh i'll take a look into that

**Comment by cazala** [comment]
`workerTrain` has been deprecated in [v1.0.6](https://github.com/cazala/synaptic/releases/tag/1.0.6) in favor of `trainAsync`
