### ISSUE TITLE
Publish the latest release on npm

### ISSUE THREAD

**Issue by kennynaoh** [cazala/synaptic#91]
Hello @cazala ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
I saw the latest release version on [github](https://github.com/cazala/synaptic) is 1.0.4.
But the latest release on [npm](https://www.npmjs.com/package/synaptic) is 1.0.2.
Maybe you could publish the latest release on npm.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/7991

**Comment by cazala** [comment]
@kennynaoh done -> https://www.npmjs.com/package/synaptic (:
