### ISSUE TITLE
L2 weight regularization

### ISSUE THREAD

**Issue by chris-rcn** [cazala/synaptic#94]
I tried to implement L2 weight regularization (periodically multiply all non-bias weights by a number slightly smaller than 1) but couldn't get it to work do to the difficult-to-follow optimization.  Any pointers?

Thanks.

**Comment by chris-rcn** [comment]
Never mind.  Figured it out.  Looks something like this:

$ git diff synaptic-src/network.js | grep -i regularization
+    for (var currentLayer in optimized.regularization_sentences)
+      for (var currentNeuron in optimized.regularization_sentences[currentLayer])
+        hardcode += optimized.regularization_sentences[currentLayer][currentNeuron].join(" ") + " ";
+      regularize: optimized.regularization_sentences,

$ git diff synaptic-src/neuron.js | grep -i regularization
+    var store_regularization = [];
+    var regularization_sentences = optimized.regularization_sentences || [];
+    allocate(regularization_sentences);
+      regularization_sentences[currentLayer].push(store_regularization);
+          buildSentence(input_weight, ' *= scale', store_regularization);
+            buildSentence(input_weight, ' *= scale', store_regularization);
+      regularization_sentences: regularization_sentences,
`

**Comment by mdeeds** [comment]
Will this be part of Version 2?
